package good.services;
/**
 * @author Arthur Tristram, Software Engineer(Java)
 * @since 2025-12-18
 * @implNote This class handles the responsibility of reading the file
 */
public class SearchVolumeService {
    /**
     * @param term the record to be processed
     * @return volume generated by a random API call
     */
    public double getVolume(String term) {
        System.out.printf("[API] Fetching volume for: %s%n", term);
        return Math.floor(Math.random() * 1000);
    }
}
